"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type Organisation = { id: string; name: string; role: string };
type Data = {
  participants: Array<Record<string, unknown>>;
  cards: Array<Record<string, unknown>>;
  memberships: Array<Record<string, unknown>>;
  shifts: Array<Record<string, unknown>>;
  assignments: Array<Record<string, unknown>>;
  authorities: Array<Record<string, unknown>>;
  grants: Array<Record<string, unknown>>;
  availability: Array<Record<string, unknown>>;
  audit: Array<Record<string, unknown>>;
};

const id = () => crypto.randomUUID();
const isoTomorrow = () => new Date(Date.now() + 86400000).toISOString().slice(0, 16);

export function AdminWorkspace({ organisation, initialData }: { organisation: Organisation; initialData: Data }) {
  const [tab, setTab] = useState("overview");
  const [data] = useState(initialData);
  const [message, setMessage] = useState("");
  const supabase = useMemo(() => createSupabaseBrowserClient(), []);
  const workers = data.memberships.filter((m) => m.role === "worker");

  async function call(name: string, args: Record<string, unknown>) {
    setMessage("Saving securely…");
    const { error } = await supabase.rpc(name, args);
    if (error) { setMessage(error.message.replace(/^.*?: /, "")); return false; }
    setMessage("Saved and added to the audit timeline.");
    window.location.reload();
    return true;
  }

  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div><p className="text-sm font-medium text-muted-foreground">{organisation.name} · {organisation.role}</p><h1 className="text-3xl font-semibold tracking-tight">Admin workspace</h1></div>
          <span className="rounded-full border border-success/40 bg-success/10 px-3 py-1 text-sm text-success-foreground">Synthetic workspace</span>
        </div>
        <p className="max-w-3xl text-sm text-muted-foreground">Prepare pilot records with separate participant identity, authority evidence, roster history, and external disclosure grants. Sensitive changes are recorded by a protected transaction.</p>
      </header>

      <nav aria-label="Admin workspace sections" className="flex flex-wrap gap-2 border-b pb-3">
        {["overview", "participants", "roster", "access", "audit"].map((item) => <Button key={item} variant={tab === item ? "default" : "outline"} onClick={() => setTab(item)} aria-current={tab === item ? "page" : undefined}>{item[0].toUpperCase() + item.slice(1)}</Button>)}
      </nav>
      {message ? <p role="status" className="rounded-md border border-info/40 bg-info/10 px-3 py-2 text-sm">{message}</p> : null}

      {tab === "overview" ? <Overview data={data} setTab={setTab} /> : null}
      {tab === "participants" ? <Participants data={data} organisationId={organisation.id} call={call} /> : null}
      {tab === "roster" ? <Roster data={data} workers={workers} organisationId={organisation.id} call={call} /> : null}
      {tab === "access" ? <Access data={data} organisationId={organisation.id} call={call} /> : null}
      {tab === "audit" ? <Audit data={data} /> : null}
    </div>
  );
}

function Overview({ data, setTab }: { data: Data; setTab: (tab: string) => void }) {
  const cards = [{ label: "Participants", value: data.participants.length, tab: "participants" }, { label: "Workers", value: data.memberships.filter((m) => m.role === "worker").length, tab: "roster" }, { label: "Upcoming shifts", value: data.shifts.filter((s) => s.state === "scheduled").length, tab: "roster" }, { label: "Active grants", value: data.grants.filter((g) => g.status === "active").length, tab: "access" }];
  return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => <button key={card.label} className="text-left" onClick={() => setTab(card.tab)}><Card className="h-full transition hover:ring-2 hover:ring-ring"><CardHeader><CardDescription>{card.label}</CardDescription><CardTitle className="text-3xl">{card.value}</CardTitle></CardHeader><CardContent><span className="text-sm text-muted-foreground">Open workspace →</span></CardContent></Card></button>)}</div>;
}

function Participants({ data, organisationId, call }: { data: Data; organisationId: string; call: (name: string, args: Record<string, unknown>) => Promise<boolean> }) {
  const [firstName, setFirstName] = useState(""); const [lastInitial, setLastInitial] = useState(""); const [critical, setCritical] = useState(""); const [due, setDue] = useState(isoTomorrow()); const [criticalParticipant, setCriticalParticipant] = useState(""); const [updatedCritical, setUpdatedCritical] = useState("");
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]">
    <Card><CardHeader><CardTitle>Create participant</CardTitle><CardDescription>Identity and minimum critical handoff are created together, but remain separate records.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); void call("cmd_admin_create_participant", { p_command_id: id(), p_organisation_id: organisationId, p_first_name: firstName, p_last_initial: lastInitial, p_critical_content: critical, p_review_due_at: new Date(due).toISOString(), p_payload: { source: "admin-workspace" } }); }}>
      <Field label="First name"><Input required value={firstName} onChange={(e) => setFirstName(e.target.value)} placeholder="Synthetic participant" /></Field>
      <Field label="Last initial"><Input maxLength={3} value={lastInitial} onChange={(e) => setLastInitial(e.target.value)} placeholder="R" /></Field>
      <Field label="Critical support and safety handoff"><textarea required value={critical} onChange={(e) => setCritical(e.target.value)} className="min-h-28 w-full rounded-md border bg-transparent p-3 text-base" placeholder="Minimum worker-visible information; no clinical approval claim." /></Field>
      <Field label="Review due"><Input required type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} /></Field>
      <Button type="submit">Create secure record</Button>
    </form></CardContent></Card>
    <Card><CardHeader><CardTitle>Participant register</CardTitle><CardDescription>Names are intentionally minimised. Open a participant to review separate authority and sharing evidence.</CardDescription></CardHeader><CardContent><div className="space-y-3">{data.participants.length ? data.participants.map((p) => { const card = data.cards.find((c) => c.participant_id === p.id); return <div key={String(p.id)} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{String(p.first_name)} {p.last_initial ? `${String(p.last_initial)}.` : ""}</strong><span className="text-xs text-muted-foreground">Created {new Date(String(p.created_at)).toLocaleDateString("en-AU")}</span></div><p className="mt-2 text-sm text-muted-foreground">Critical handoff: {card ? `review due ${new Date(String(card.review_due_at)).toLocaleDateString("en-AU")}` : "missing — contact provider"}</p></div>; }) : <EmptyState text="No participants yet. Use the form to prepare a synthetic participant." />}</div><form className="mt-5 space-y-4 border-t pt-5" onSubmit={(e) => { e.preventDefault(); void call("cmd_admin_update_critical_info", { p_command_id: id(), p_organisation_id: organisationId, p_participant_id: criticalParticipant, p_critical_content: updatedCritical, p_review_due_at: new Date(due).toISOString(), p_payload: { source: "admin-workspace" } }); }}><Field label="Participant to review"><select required value={criticalParticipant} onChange={(e) => setCriticalParticipant(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose participant</option>{data.participants.map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.first_name)}</option>)}</select></Field><Field label="Updated critical handoff"><textarea required value={updatedCritical} onChange={(e) => setUpdatedCritical(e.target.value)} className="min-h-24 w-full rounded-md border bg-transparent p-3 text-base" /></Field><Button type="submit" variant="outline">Publish reviewed handoff</Button></form></CardContent></Card>
  </div>;
}

function Roster({ data, workers, organisationId, call }: { data: Data; workers: Array<Record<string, unknown>>; organisationId: string; call: (name: string, args: Record<string, unknown>) => Promise<boolean> }) {
  const [participant, setParticipant] = useState(""); const [worker, setWorker] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [reason, setReason] = useState(""); const [availabilityFrom, setAvailabilityFrom] = useState(""); const [availabilityUntil, setAvailabilityUntil] = useState(""); const [availabilityNote, setAvailabilityNote] = useState(""); const [reassignShift, setReassignShift] = useState(""); const [reassignWorker, setReassignWorker] = useState(""); const [reassignReason, setReassignReason] = useState("");
  return <div className="space-y-6"><Card><CardHeader><CardTitle>Create roster shift</CardTitle><CardDescription>Overlap and published-availability warnings return with the transaction; a warning does not silently hide the assignment.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); void call("cmd_admin_create_shift", { p_command_id: id(), p_organisation_id: organisationId, p_participant_id: participant, p_worker_membership: worker, p_scheduled_start: new Date(start).toISOString(), p_scheduled_end: new Date(end).toISOString(), p_reason: reason, p_payload: { source: "admin-workspace" } }); }}>
    <Field label="Participant"><select required value={participant} onChange={(e) => setParticipant(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose participant</option>{data.participants.map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.first_name)} {String(p.last_initial ?? "")}</option>)}</select></Field>
    <Field label="Worker"><select required value={worker} onChange={(e) => setWorker(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose worker membership</option>{workers.map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.profile_id)} · worker</option>)}</select></Field>
    <Field label="Scheduled start"><Input required type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} /></Field><Field label="Scheduled end"><Input required type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} /></Field>
    <Field label="Assignment reason"><Input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Routine roster / cover" /></Field><div className="flex items-end"><Button type="submit">Create shift</Button></div>
  </form></CardContent></Card>
  <Card><CardHeader><CardTitle>Published worker availability</CardTitle><CardDescription>Availability is advisory. A shift outside this window is warned, not silently discarded.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); void call("cmd_admin_set_availability", { p_command_id: id(), p_organisation_id: organisationId, p_worker_membership: worker, p_available_from: new Date(availabilityFrom).toISOString(), p_available_until: new Date(availabilityUntil).toISOString(), p_note: availabilityNote, p_payload: { source: "admin-workspace" } }); }}><Field label="Worker"><select required value={worker} onChange={(e) => setWorker(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose worker membership</option>{workers.map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.profile_id)}</option>)}</select></Field><Field label="Note"><Input value={availabilityNote} onChange={(e) => setAvailabilityNote(e.target.value)} placeholder="School hours / regular window" /></Field><Field label="Available from"><Input required type="datetime-local" value={availabilityFrom} onChange={(e) => setAvailabilityFrom(e.target.value)} /></Field><Field label="Available until"><Input required type="datetime-local" value={availabilityUntil} onChange={(e) => setAvailabilityUntil(e.target.value)} /></Field><div><Button type="submit" variant="outline">Publish availability</Button></div></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Reassign a shift</CardTitle><CardDescription>The current assignment is withdrawn, the new assignment is appended, and the reason remains visible in the audit history.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); const selected = data.shifts.find((s) => s.id === reassignShift); if (!selected) return; void call("cmd_reassign_shift", { p_command_id: id(), p_shift_id: reassignShift, p_expected_version: selected.version, p_claimed_at: new Date().toISOString(), p_client_tz: "Australia/Sydney", p_new_worker_membership: reassignWorker, p_reason: reassignReason, p_payload: { source: "admin-workspace" } }); }}><Field label="Shift"><select required value={reassignShift} onChange={(e) => setReassignShift(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose shift</option>{data.shifts.map((s) => <option key={String(s.id)} value={String(s.id)}>{new Date(String(s.scheduled_start)).toLocaleString("en-AU")} · v{String(s.version)}</option>)}</select></Field><Field label="New worker"><select required value={reassignWorker} onChange={(e) => setReassignWorker(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose worker membership</option>{workers.map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.profile_id)}</option>)}</select></Field><Field label="Reason"><Input required value={reassignReason} onChange={(e) => setReassignReason(e.target.value)} placeholder="Cover confirmed with worker" /></Field><div className="flex items-end"><Button type="submit" variant="outline">Reassign shift</Button></div></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Roster and audit-friendly assignment history</CardTitle><CardDescription>Reassignment uses the existing versioned command and never erases prior assignments.</CardDescription></CardHeader><CardContent><div className="space-y-3">{data.shifts.length ? data.shifts.map((shift) => { const assignment = data.assignments.find((a) => a.shift_id === shift.id && !a.withdrawn_at); const p = data.participants.find((item) => item.id === shift.participant_id); return <div key={String(shift.id)} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{String(p?.first_name ?? "Participant")}</strong><span className="rounded-full bg-muted px-2 py-1 text-xs">{String(shift.state)}</span></div><p className="mt-1 text-sm">{new Date(String(shift.scheduled_start)).toLocaleString("en-AU")} – {new Date(String(shift.scheduled_end)).toLocaleTimeString("en-AU", { hour: "2-digit", minute: "2-digit" })}</p><p className="text-xs text-muted-foreground">Current worker membership: {String(assignment?.membership_id ?? "unassigned")} · version {String(shift.version)}</p></div>; }) : <EmptyState text="No shifts yet. Create a synthetic roster assignment above." />}</div></CardContent></Card></div>;
}

function Access({ data, organisationId, call }: { data: Data; organisationId: string; call: (name: string, args: Record<string, unknown>) => Promise<boolean> }) {
  const [email, setEmail] = useState(""); const [role, setRole] = useState("worker"); const [inviteExpiry, setInviteExpiry] = useState(isoTomorrow()); const [purpose, setPurpose] = useState(""); const [scope, setScope] = useState("service_summary"); const [participant, setParticipant] = useState(""); const [recipient, setRecipient] = useState(""); const [consent, setConsent] = useState(""); const [evidence, setEvidence] = useState(""); const [authorityType, setAuthorityType] = useState("plan_nominee"); const [authorityScope, setAuthorityScope] = useState("upcoming_visits,service_summary"); const [selfEvidence, setSelfEvidence] = useState("");
  return <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Invite a role</CardTitle><CardDescription>Invitations are single-use, expiring, and do not reveal whether the email belongs to another organisation.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); void call("cmd_admin_invite", { p_command_id: id(), p_organisation_id: organisationId, p_email: email, p_role: role, p_expires_at: new Date(inviteExpiry).toISOString(), p_payload: { source: "admin-workspace" } }); }}><Field label="Email"><Input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></Field><Field label="Role"><select value={role} onChange={(e) => setRole(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option>worker</option><option>scheduler</option><option>participant</option><option>nominee</option><option>external</option></select></Field><Field label="Expires"><Input required type="datetime-local" value={inviteExpiry} onChange={(e) => setInviteExpiry(e.target.value)} /></Field><Button type="submit">Issue invitation</Button></form></CardContent></Card>
  <Card><CardHeader><CardTitle>External view-only grant</CardTitle><CardDescription>Purpose, scope, consent basis, evidence, effective period, and recipient are mandatory. Previously disclosed copies cannot be remotely recalled.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); const from = new Date(); const until = new Date(Date.now() + 30 * 86400000); void call("cmd_admin_create_grant", { p_command_id: id(), p_organisation_id: organisationId, p_participant_id: participant, p_recipient_profile_id: recipient, p_purpose: purpose, p_scope_categories: scope.split(",").map((s) => s.trim()).filter(Boolean), p_consent_basis: "participant", p_consent_reference: consent, p_evidence_reference: evidence, p_effective_from: from.toISOString(), p_effective_until: until.toISOString(), p_payload: { source: "admin-workspace" } }); }}><Field label="Participant"><select required value={participant} onChange={(e) => setParticipant(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose participant</option>{data.participants.map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.first_name)} {String(p.last_initial ?? "")}</option>)}</select></Field><Field label="Recipient profile ID"><Input required value={recipient} onChange={(e) => setRecipient(e.target.value)} placeholder="Invitee profile UUID" /></Field><Field label="Purpose"><Input required value={purpose} onChange={(e) => setPurpose(e.target.value)} placeholder="Coordinate supports" /></Field><Field label="Record scope"><Input required value={scope} onChange={(e) => setScope(e.target.value)} /></Field><Field label="Consent reference"><Input required value={consent} onChange={(e) => setConsent(e.target.value)} placeholder="Participant consent record" /></Field><Field label="Evidence reference"><Input required value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="Document or case reference" /></Field><Button type="submit">Create view-only grant</Button></form></CardContent></Card>
  <Card className="lg:col-span-2"><CardHeader><CardTitle>Current disclosures and authority</CardTitle><CardDescription>These are separate concepts. A representative authority never becomes an external grant automatically.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{data.grants.map((grant) => <div key={String(grant.id)} className="rounded-lg border p-4"><div className="flex justify-between gap-2"><strong>{String(grant.purpose)}</strong><span className="text-xs">{String(grant.status)}</span></div><p className="text-sm text-muted-foreground">Scope: {Array.isArray(grant.scope_categories) ? (grant.scope_categories as string[]).join(", ") : String(grant.scope_categories)}</p><p className="text-xs text-muted-foreground">Recipient {String(grant.recipient_profile_id)} · expires {new Date(String(grant.effective_until)).toLocaleDateString("en-AU")}</p>{grant.status === "active" ? <Button className="mt-3" size="sm" variant="destructive" onClick={() => void call("cmd_admin_revoke_grant", { p_command_id: id(), p_organisation_id: organisationId, p_grant_id: grant.id, p_reason: "Withdrawn by authorised provider user", p_payload: { source: "admin-workspace" } })}>Revoke grant</Button> : null}</div>)}{!data.grants.length ? <EmptyState text="No external disclosure grants recorded." /> : null}</div></CardContent></Card>
  <Card><CardHeader><CardTitle>Participant self-link</CardTitle><CardDescription>Self-access is separate from external disclosure and representative authority.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); void call("cmd_admin_link_participant", { p_command_id: id(), p_organisation_id: organisationId, p_participant_id: participant, p_profile_id: recipient, p_evidence_reference: selfEvidence, p_payload: { source: "admin-workspace" } }); }}><Field label="Participant"><select required value={participant} onChange={(e) => setParticipant(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose participant</option>{data.participants.map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.first_name)}</option>)}</select></Field><Field label="Participant profile ID"><Input required value={recipient} onChange={(e) => setRecipient(e.target.value)} placeholder="Invited participant UUID" /></Field><Field label="Evidence reference"><Input required value={selfEvidence} onChange={(e) => setSelfEvidence(e.target.value)} /></Field><Button type="submit" variant="outline">Link self-access</Button></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Representative authority</CardTitle><CardDescription>Record relationship, scope, evidence, issuer, and effective period independently.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); const from = new Date(); const until = new Date(Date.now() + 90 * 86400000); void call("cmd_admin_set_authority", { p_command_id: id(), p_organisation_id: organisationId, p_participant_id: participant, p_representative_profile_id: recipient, p_authority_type: authorityType, p_scope_categories: authorityScope.split(",").map((s) => s.trim()).filter(Boolean), p_evidence_reference: evidence, p_issuer: "Provider admin", p_effective_from: from.toISOString(), p_effective_until: until.toISOString(), p_payload: { source: "admin-workspace" } }); }}><Field label="Participant"><select required value={participant} onChange={(e) => setParticipant(e.target.value)} className="h-9 w-full rounded-md border bg-background px-2"><option value="">Choose participant</option>{data.participants.map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.first_name)}</option>)}</select></Field><Field label="Representative profile ID"><Input required value={recipient} onChange={(e) => setRecipient(e.target.value)} /></Field><Field label="Authority type"><Input required value={authorityType} onChange={(e) => setAuthorityType(e.target.value)} /></Field><Field label="Scope categories"><Input required value={authorityScope} onChange={(e) => setAuthorityScope(e.target.value)} /></Field><Field label="Evidence reference"><Input required value={evidence} onChange={(e) => setEvidence(e.target.value)} /></Field><Button type="submit" variant="outline">Record authority</Button></form></CardContent></Card>
  </div>;
}

function Audit({ data }: { data: Data }) { return <Card><CardHeader><CardTitle>Audit timeline</CardTitle><CardDescription>Read-only visibility for invitations, roster changes, authority, grants, and participant records.</CardDescription></CardHeader><CardContent><ol className="space-y-3">{data.audit.length ? data.audit.map((entry) => <li key={String(entry.id)} className="border-l-2 border-primary/30 pl-4"><div className="flex flex-wrap justify-between gap-2"><strong>{String(entry.action)}</strong><time className="text-xs text-muted-foreground">{new Date(String(entry.created_at)).toLocaleString("en-AU")}</time></div><p className="text-xs text-muted-foreground">{String(entry.subject_type)} · {String(entry.subject_id)} · actor {String(entry.actor)}</p></li>) : <EmptyState text="Audit events will appear here after the first secure command." />}</ol></CardContent></Card>; }

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function EmptyState({ text }: { text: string }) { return <div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">{text}</div>; }
